#!/bin/bash

if [ -f ./setup ]
then
  ./setup
fi

STARTCMD="/usr/bin/redis-server"

if [ -n "${REDIS_BACKLOG}" ]
then
  STARTCMD="${STARTCMD} --tcp-backlog ${REDIS_BACKLOG}"
else
  STARTCMD="${STARTCMD} --tcp-backlog 511"
fi

if [ -n "${REDIS_KEEPALIVE}" ]
then
  STARTCMD="${STARTCMD} --tcp-keepalive ${REDIS_KEEPALIVE}"
else
  STARTCMD="${STARTCMD} --tcp-keepalive 0"
fi

if [ -n "${REDIS_TIMEOUT}" ]
then
  STARTCMD="${STARTCMD} --timeout ${REDIS_TIMEOUT}"
else
  STARTCMD="${STARTCMD} --timeout 0"
fi

if [ -n "${REDIS_LOGLEVEL}" ]
then
  STARTCMD="${STARTCMD} --loglevel ${REDIS_LOGLEVEL}"
else
  STARTCMD="${STARTCMD} --loglevel notice"
fi

if [ -n "${REDIS_DATABASES}" ]
then
  STARTCMD="${STARTCMD} --databases ${REDIS_DATABASES}"
else
  STARTCMD="${STARTCMD} --databases 16"
fi

if [ -n "${REDIS_MAXCONN}" ]
then
  STARTCMD="${STARTCMD} --maxclients ${REDIS_MAXCONN}"
else
  STARTCMD="${STARTCMD} --maxclients 10000"
fi

if [ -n "${REDIS_NOTIFYKS}" ]
then
  STARTCMD="${STARTCMD} --notify-keyspace-events ${REDIS_NOTIFYKS}"
else
  STARTCMD="${STARTCMD} --notify-keyspace-events Elg"
fi

if [ -n "${REDIS_OPTS}" ]
then
  STARTCMD="${STARTCMD} ${REDIS_OPTS}"
fi

exec ${STARTCMD}
