FROM ghcr.io/dockhippie/alpine:latest-amd64@sha256:e88daf2110eb7e3d851af3d03c8bd6068b43cc9a9b9764413e88fa9c4cffac8e

VOLUME ["/var/lib/redis"]
EXPOSE 6379

WORKDIR /var/lib/redis
CMD ["/usr/bin/container"]

RUN apk update && \
  apk upgrade && \
  mkdir -p /var/lib/redis && \
  groupadd -g 1000 redis && \
  useradd -u 1000 -d /var/lib/redis -g redis -s /bin/bash -m redis && \
  apk add redis && \
  rm -rf /var/cache/apk/*

COPY ./overlay /
