FROM webhippie/alpine:latest-arm32v6@sha256:e974574e5a59c39564f075610a5e157c9053ed12d809d1c20d724687b2975311

LABEL maintainer="Thomas Boerger <thomas@webhippie.de>" \
  org.label-schema.name="Redis" \
  org.label-schema.vcs-url="https://github.com/dockhippie/redis.git" \
  org.label-schema.vendor="Thomas Boerger" \
  org.label-schema.schema-version="1.0"

EXPOSE 6379

VOLUME ["/var/lib/redis"]
WORKDIR /root
ENTRYPOINT ["/usr/bin/entrypoint"]
CMD ["/bin/s6-svscan", "/etc/s6"]

RUN apk update && \
  apk upgrade && \
  mkdir -p /var/lib/redis && \
  apk add redis && \
  rm -rf /var/cache/apk/*

COPY ./overlay ./overlay-arm32v6 /
