FROM ghcr.io/dockhippie/alpine:latest-amd64@sha256:fdce6f26d9bc8729c9e1377b2f69ef1d4fa5415b83035df2fb9e282d520d11cd

VOLUME ["/var/lib/redis"]
EXPOSE 6379

WORKDIR /var/lib/redis
CMD ["/usr/bin/container"]

RUN apk update && \
  apk upgrade && \
  mkdir -p /var/lib/redis && \
  groupadd -g 1000 redis && \
  useradd -u 1000 -d /var/lib/redis -g redis -s /bin/bash -m redis && \
  apk add redis && \
  rm -rf /var/cache/apk/*

COPY ./overlay /

RUN find /etc/container.d /etc/entrypoint.d -type f -name \*.sh -exec sed -i 's/\r$//' {} +; \
  sed -i 's/\r$//' /usr/bin/healthcheck /usr/bin/container && \
  chmod +x /usr/bin/healthcheck /usr/bin/container /etc/container.d/*.sh /etc/entrypoint.d/*.sh
