FROM webhippie/alpine:latest-arm64@sha256:c020655b2394058dbe4352dccc6d176b05ad0bd6d77ee5d28d58c2d4780e0034

VOLUME ["/var/lib/redis"]
EXPOSE 6379

WORKDIR /var/lib/redis
CMD ["/usr/bin/container"]

RUN apk update && \
  apk upgrade && \
  mkdir -p /var/lib/redis && \
  groupadd -g 1000 redis && \
  useradd -u 1000 -d /var/lib/redis -g redis -s /bin/bash -m redis && \
  apk add redis && \
  rm -rf /var/cache/apk/*

COPY ./overlay /
