FROM webhippie/alpine:latest-arm64v8@sha256:248d3c19cd10e084aee1ad346ba0b1068d5cdeed5ef3dce5dce3e0ec26a07eb8

LABEL maintainer="Thomas Boerger <thomas@webhippie.de>" \
  org.label-schema.name="Redis" \
  org.label-schema.vcs-url="https://github.com/dockhippie/redis.git" \
  org.label-schema.vendor="Thomas Boerger" \
  org.label-schema.schema-version="1.0"

EXPOSE 6379

VOLUME ["/var/lib/redis"]
WORKDIR /root
ENTRYPOINT ["/usr/bin/entrypoint"]
CMD ["/bin/s6-svscan", "/etc/s6"]

RUN apk update && \
  apk upgrade && \
  mkdir -p /var/lib/redis && \
  apk add redis && \
  rm -rf /var/cache/apk/*

COPY ./overlay ./overlay-arm64v8 /
