FROM webhippie/alpine:latest-arm32v6@sha256:f52146000ae31a8e6df968e3ab3680f5d799b1e5cb2100fa90ec71584068b0a7

LABEL maintainer="Thomas Boerger <thomas@webhippie.de>" \
  org.label-schema.name="Redis" \
  org.label-schema.vcs-url="https://github.com/dockhippie/redis.git" \
  org.label-schema.vendor="Thomas Boerger" \
  org.label-schema.schema-version="1.0"

EXPOSE 6379

VOLUME ["/var/lib/redis"]
WORKDIR /root
ENTRYPOINT ["/usr/bin/entrypoint"]
CMD ["/bin/s6-svscan", "/etc/s6"]

RUN apk update && \
  apk upgrade && \
  mkdir -p /var/lib/redis && \
  apk add redis && \
  rm -rf /var/cache/apk/*

COPY ./overlay ./overlay-arm32v6 /
