FROM ghcr.io/dockhippie/alpine:latest-arm64@sha256:bf2c966548f93edeee7a9dfc03b98f1ed7ed9ccd6503b50912be86b486d16fc8

VOLUME ["/var/lib/redis"]
EXPOSE 6379

WORKDIR /var/lib/redis
CMD ["/usr/bin/container"]

RUN apk update && \
  apk upgrade && \
  mkdir -p /var/lib/redis && \
  groupadd -g 1000 redis && \
  useradd -u 1000 -d /var/lib/redis -g redis -s /bin/bash -m redis && \
  apk add redis && \
  rm -rf /var/cache/apk/*

COPY ./overlay /
