FROM webhippie/alpine:latest-arm64v8@sha256:2af125d3829f11d05c99396f5a29d5592f6d44fb37d9c384497fdd7beef62c5b

LABEL maintainer="Thomas Boerger <thomas@webhippie.de>" \
  org.label-schema.name="Redis" \
  org.label-schema.vcs-url="https://github.com/dockhippie/redis.git" \
  org.label-schema.vendor="Thomas Boerger" \
  org.label-schema.schema-version="1.0"

EXPOSE 6379

VOLUME ["/var/lib/redis"]
WORKDIR /root
ENTRYPOINT ["/usr/bin/entrypoint"]
CMD ["/bin/s6-svscan", "/etc/s6"]

RUN apk update && \
  apk upgrade && \
  mkdir -p /var/lib/redis && \
  apk add redis && \
  rm -rf /var/cache/apk/*

COPY ./overlay ./overlay-arm64v8 /
