FROM ghcr.io/dockhippie/alpine:latest-arm@sha256:5774acc36d6aaf409682e6aa078253ecb7a5cea33572165cbf9212586d3ec97a

VOLUME ["/var/lib/redis"]
EXPOSE 6379

WORKDIR /var/lib/redis
CMD ["/usr/bin/container"]

RUN apk update && \
  apk upgrade && \
  mkdir -p /var/lib/redis && \
  groupadd -g 1000 redis && \
  useradd -u 1000 -d /var/lib/redis -g redis -s /bin/bash -m redis && \
  apk add redis && \
  rm -rf /var/cache/apk/*

COPY ./overlay /
