#!/usr/bin/env bash
# Usage: manage prepare
# Summary: Prepare environment
# Help: This command is used to prepare the environment for the container.
set -e
[[ -z $_MANAGE_ROOT ]] && exit 1

chown -R redis:redis \
  /var/lib/redis
