#!/usr/bin/env bash
# Usage: manage running
# Summary: Check if Redis is running
# Help: This command is used to check if the Redis server process is running.
set -e
[[ -z $_MANAGE_ROOT ]] && exit 1

if [ "$(manage-pid)" == "" ]
then
  exit 1
else
  exit 0
fi
