#!/usr/bin/env bash
# Usage: manage start
# Summary: Start the Redis server
# Help: This command is used to really start the Redis server process.
set -e
[[ -z $_MANAGE_ROOT ]] && exit 1

if manage-running
then
  echo "Server is already running"
else
  manage-prepare && /usr/bin/redis-server --tcp-backlog ${REDIS_BACKLOG} --tcp-keepalive ${REDIS_KEEPALIVE} --timeout ${REDIS_TIMEOUT} --loglevel ${REDIS_LOGLEVEL} --databases ${REDIS_DATABASES} --maxclients ${REDIS_MAXCONN} --notify-keyspace-events ${REDIS_NOTIFYKS} ${REDIS_OPTS}
fi
